### ISSUE TITLE
Performance Issues 

### ISSUE THREAD

**Issue by AttackKittens** [JHay0112/lgui#7]
On Windows 10 and Mac OS Python 3.10, the mouse movements are significantly delayed.

**Comment by JHay0112** [comment]
Hi, I've had a look into this and done some testing, it appears this was to do with the _refresh method in the Editor class. This was wrapped with the @_draws decorator which caused the next refresh thread to be spawned within the canvas hold. Testing with the `mouse-speed-up` branch should hopefully show this to be the case too.
